name: R Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: install project
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.0

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install devtools dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("devtools","testthat"))'

    - name: Run tests
      run: |
        Rscript -e 'devtools::install()'
        Rscript -e 'devtools::test()'
