name: R Test on Ubuntu 18.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: install project
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.0

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("devtools", "randomifyR"))'

    - name: Run tests
      run: |
        Rscript -e 'devtools::test()'
